# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 31) do

  create_table "ytapl_addressinfo", :force => true do |t|
    t.column "taskid", :string, :limit => 100
    t.column "unitid", :string, :limit => 100
    t.column "email", :string, :limit => 100
    t.column "mobile", :string, :limit => 100
    t.column "phone", :string, :limit => 100
    t.column "fax", :string, :limit => 100
    t.column "flag", :integer
    t.column "reserved1", :string, :limit => 100
    t.column "reserved2", :string, :limit => 100
    t.column "reserved3", :string, :limit => 100
  end

  create_table "ytapl_article_template", :force => true do |t|
    t.column "taskid", :string, :limit => 100
    t.column "publishtime", :datetime
    t.column "name", :string, :limit => 100
    t.column "context", :text
  end

  create_table "ytapl_auditinfo", :id => false, :force => true do |t|
    t.column "unitid", :string, :limit => 100
    t.column "taskid", :string, :limit => 100
    t.column "tasktimeid", :integer
    t.column "auditdate", :datetime
    t.column "flag", :integer
    t.column "auditor", :string, :limit => 100
  end

  create_table "ytapl_bbsmessage", :force => true do |t|
    t.column "username", :string, :limit => 50
    t.column "time", :datetime
    t.column "title", :string, :limit => 200
    t.column "content", :text
    t.column "reserved1", :string, :limit => 100
    t.column "reserved2", :string, :limit => 100
    t.column "reserved3", :string, :limit => 100
    t.column "reserved4", :string, :limit => 100
    t.column "reserved5", :string, :limit => 100
    t.column "reserved6", :string, :limit => 100
  end

  create_table "ytapl_browselog", :force => true do |t|
    t.column "news_id", :integer
    t.column "username", :string, :limit => 100
    t.column "browsetime", :datetime
    t.column "address", :string, :limit => 100
  end

  create_table "ytapl_converttask", :force => true do |t|
    t.column "taskid", :integer
    t.column "name", :string, :limit => 100
    t.column "publishtime", :date
    t.column "content", :text
    t.column "reserved1", :string, :limit => 100
    t.column "reserved2", :string, :limit => 100
    t.column "reserved3", :string, :limit => 100
    t.column "reserved4", :string, :limit => 100
    t.column "reserved5", :string, :limit => 100
    t.column "reserved6", :string, :limit => 100
  end

  create_table "ytapl_cookies", :force => true do |t|
    t.column "addr", :string, :limit => 50
    t.column "lasttask", :integer
    t.column "reserved1", :string, :limit => 100
    t.column "reserved2", :string, :limit => 100
    t.column "reserved3", :string, :limit => 100
    t.column "reserved4", :string, :limit => 100
    t.column "reserved5", :string, :limit => 100
    t.column "reserved6", :string, :limit => 100
  end

  create_table "ytapl_dataevents", :id => false, :force => true do |t|
    t.column "eventid", :integer, :null => false
    t.column "timeoccured", :datetime
    t.column "eventtype", :integer
    t.column "source", :string, :limit => 100
    t.column "username", :string, :limit => 100
    t.column "memo", :text
  end

  create_table "ytapl_draft", :force => true do |t|
    t.column "unitid", :string, :limit => 100
    t.column "taskid", :integer
    t.column "tasktimeid", :integer
    t.column "content", :text
    t.column "reserved1", :string, :limit => 100
    t.column "reserved2", :string, :limit => 100
    t.column "reserved3", :string, :limit => 100
  end

  create_table "ytapl_fileshare", :force => true do |t|
    t.column "userid", :string, :limit => 100
    t.column "name", :string, :limit => 100
    t.column "sender", :string, :limit => 100
    t.column "uploadtime", :datetime
    t.column "path", :string, :limit => 200
    t.column "reserved1", :string, :limit => 100
    t.column "reserved2", :string, :limit => 100
    t.column "reserved3", :string, :limit => 100
  end

  create_table "ytapl_fillstate", :id => false, :force => true do |t|
    t.column "unitid", :string, :limit => 50
    t.column "taskid", :string, :limit => 50
    t.column "tasktimeid", :integer
    t.column "filldate", :datetime
    t.column "flag", :integer
    t.column "ext1", :integer
    t.column "ext2", :integer
    t.column "ext3", :integer
    t.column "ext4", :integer
  end

  create_table "ytapl_groupmember", :id => false, :force => true do |t|
    t.column "groupid", :integer
    t.column "userid", :integer
  end

  create_table "ytapl_groups", :id => false, :force => true do |t|
    t.column "groupid", :integer, :null => false
    t.column "name", :string, :limit => 100
    t.column "datecreated", :datetime
    t.column "datemodified", :datetime
    t.column "flag", :integer
    t.column "memo", :string, :limit => 100
    t.column "reserved1", :string, :limit => 100
    t.column "reserved2", :string, :limit => 100
    t.column "reserved3", :string, :limit => 100
  end

  create_table "ytapl_news", :force => true do |t|
    t.column "title", :string, :limit => 200
    t.column "content", :text
    t.column "publish_time", :datetime
    t.column "reserved1", :string, :limit => 100
    t.column "reserved2", :string, :limit => 100
    t.column "reserved3", :string, :limit => 100
    t.column "reserved4", :string, :limit => 100
    t.column "reserved5", :string, :limit => 100
    t.column "reserved6", :string, :limit => 100
  end

  create_table "ytapl_report_template", :id => false, :force => true do |t|
    t.column "templateid", :integer, :null => false
    t.column "taskid", :string, :limit => 50
    t.column "templatename", :string, :limit => 50
    t.column "createtime", :datetime
    t.column "moditime", :datetime
    t.column "content", :text
    t.column "image", :text
    t.column "reserved1", :string, :limit => 100
    t.column "reserved2", :string, :limit => 100
    t.column "reserved3", :string, :limit => 100
    t.column "reserved4", :string, :limit => 100
  end

  create_table "ytapl_reportresult", :force => true do |t|
    t.column "templateid", :integer
    t.column "name", :string, :limit => 100
    t.column "createtime", :datetime
    t.column "context", :text
  end

  create_table "ytapl_right", :force => true do |t|
    t.column "name", :string, :limit => 100
    t.column "memo", :string, :limit => 100
  end

  create_table "ytapl_roleright", :id => false, :force => true do |t|
    t.column "role_id", :integer
    t.column "right_id", :integer
  end

  create_table "ytapl_roles", :id => false, :force => true do |t|
    t.column "roleid", :integer, :null => false
    t.column "name", :string, :limit => 100
    t.column "userrights", :string, :limit => 100
    t.column "datecreated", :datetime
    t.column "datemodified", :datetime
    t.column "flag", :integer
    t.column "memo", :string, :limit => 100
    t.column "reserved1", :string, :limit => 100
    t.column "reserved2", :string, :limit => 100
    t.column "reserved3", :string, :limit => 100
  end

  create_table "ytapl_scalarexplain", :force => true do |t|
    t.column "name", :string, :limit => 100
    t.column "content", :text
    t.column "reserved1", :string, :limit => 100
    t.column "reserved2", :string, :limit => 100
    t.column "reserved3", :string, :limit => 100
  end

  create_table "ytapl_script", :id => false, :force => true do |t|
    t.column "scriptid", :integer, :null => false
    t.column "taskid", :integer
    t.column "publishtime", :datetime
    t.column "name", :string, :limit => 100
    t.column "content", :text
  end

  create_table "ytapl_securityevents", :id => false, :force => true do |t|
    t.column "eventid", :integer, :null => false
    t.column "timeoccured", :datetime
    t.column "eventtype", :integer
    t.column "source", :string, :limit => 100
    t.column "username", :string, :limit => 100
    t.column "memo", :text
  end

  create_table "ytapl_statistic", :force => true do |t|
    t.column "cata_id", :integer
    t.column "name", :string, :limit => 100
    t.column "uploadtime", :datetime
    t.column "path", :string, :limit => 100
    t.column "reserved1", :string, :limit => 100
    t.column "reserved2", :string, :limit => 100
    t.column "reserved3", :string, :limit => 100
  end

  create_table "ytapl_statisticcatalog", :force => true do |t|
    t.column "name", :string, :limit => 100
    t.column "parent_id", :integer
    t.column "reserved1", :string, :limit => 100
    t.column "reserved2", :string, :limit => 100
    t.column "reserved3", :string, :limit => 100
  end

  create_table "ytapl_system", :force => true do |t|
    t.column "visitedtimes", :integer
    t.column "reserved1", :string, :limit => 100
    t.column "reserved2", :string, :limit => 100
    t.column "reserved3", :string, :limit => 100
    t.column "reserved4", :string, :limit => 100
    t.column "reserved5", :string, :limit => 100
    t.column "reserved6", :string, :limit => 100
  end

  create_table "ytapl_tasks", :id => false, :force => true do |t|
    t.column "taskid", :integer, :null => false
    t.column "strid", :string, :limit => 20
    t.column "name", :string, :limit => 100
    t.column "version", :integer
    t.column "flag", :integer
    t.column "datecreated", :datetime
    t.column "datemodified", :datetime
    t.column "memo", :string, :limit => 200
    t.column "content", :text
    t.column "activescriptsuitname", :string, :limit => 100
    t.column "position", :integer
    t.column "reserved1", :string, :limit => 100
    t.column "reserved2", :string, :limit => 100
    t.column "reserved3", :string, :limit => 100
  end

  create_table "ytapl_tasktimes", :id => false, :force => true do |t|
    t.column "tasktimeid", :integer, :null => false
    t.column "taskid", :integer
    t.column "begintime", :datetime
    t.column "endtime", :datetime
    t.column "submitbegintime", :datetime
    t.column "submitendtime", :datetime
    t.column "attentionbegintime", :datetime
    t.column "attentionendtime", :datetime
    t.column "flag", :integer
    t.column "reserved1", :string, :limit => 100
    t.column "reserved2", :string, :limit => 100
    t.column "reserved3", :string, :limit => 100
  end

  create_table "ytapl_taskvisible", :id => false, :force => true do |t|
    t.column "taskid", :integer
    t.column "groupid", :integer
  end

  create_table "ytapl_unitpermissions", :id => false, :force => true do |t|
    t.column "groupid", :integer
    t.column "taskid", :string, :limit => 50
    t.column "unitid", :string, :limit => 50
    t.column "permission", :integer
    t.column "endtime", :datetime
    t.column "reserved1", :string, :limit => 100
    t.column "reserved2", :string, :limit => 100
    t.column "reserved3", :string, :limit => 100
  end

  create_table "ytapl_unitschema", :id => false, :force => true do |t|
    t.column "groupid", :integer, :null => false
    t.column "taskid", :integer
    t.column "name", :string, :limit => 100
    t.column "content", :text
    t.column "reserved1", :string, :limit => 100
    t.column "reserved2", :string, :limit => 100
    t.column "reserved3", :string, :limit => 100
  end

  create_table "ytapl_users", :id => false, :force => true do |t|
    t.column "userid", :integer, :null => false
    t.column "name", :string, :limit => 100
    t.column "truename", :string, :limit => 100
    t.column "password", :string, :limit => 100
    t.column "roleid", :string, :limit => 100
    t.column "enterprisename", :string, :limit => 100
    t.column "lawpersioncode", :string, :limit => 100
    t.column "lawpersionname", :string, :limit => 100
    t.column "lawpersionphone", :string, :limit => 100
    t.column "contactpersionname", :string, :limit => 100
    t.column "contactpersionphone", :string, :limit => 100
    t.column "contactpersionmobile", :string, :limit => 100
    t.column "contactaddress", :string, :limit => 100
    t.column "postcode", :string, :limit => 100
    t.column "email", :string, :limit => 100
    t.column "fax", :string, :limit => 100
    t.column "datecreated", :datetime
    t.column "datemodified", :datetime
    t.column "flag", :integer
    t.column "memo", :string, :limit => 100
    t.column "reserved1", :string, :limit => 100
    t.column "reserved2", :string, :limit => 100
    t.column "reserved3", :string, :limit => 100
  end

end
